### ISSUE TITLE
Unable to build package in R 4.4.0

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/gfiscamutils#6]
Seems like maybe the issue is that the `rgeos` package has been archived?

==> devtools::document(roclets = c('rd', 'collate', 'namespace'))
ℹ Updating gfiscamutils documentation
ℹ Loading gfiscamutils
Error in load_imports(path) : The package "rgeos" is required.
Calls: suppressPackageStartupMessages ... load_imports -> deps_check_installed -> check_installed
Execution halted
Exited with status 1.

==> Rcmd.exe INSTALL --preclean --no-multiarch --with-keep.source gfiscamutils
* installing to library 'C:/Applications/R/R-4.4.0/library'
ERROR: dependency 'rgeos' is not available for package 'gfiscamutils'
* removing 'C:/Applications/R/R-4.4.0/library/gfiscamutils'
Exited with status 1.

> install.packages("rgeos")
Warning in install.packages :
  package ‘rgeos’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

https://cran.r-project.org/web/packages/rgeos/index.html

**Comment by cgrandin** [comment]
Yes. `rgeos` is obsolete now and no longer supported.
Delete this line and re-build the docs:
https://github.com/pbs-assess/gfiscamutils/blob/de164b339b62249e62827485e83d0cb64240b2c4/DESCRIPTION#L31

If there are any functions from `rgeos` in your branch then you need to recode those not using `rgeos`

**Comment by grinnellm** [comment]
Thanks Chris, I forgot this was just the Herring branch (I assume it's fixed on Main).
