### ISSUE TITLE
Error with updated R version R-4.4.0 in `calc.ahat()` re `is.a(mpd)` has length > 1 (Herring branch)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/gfiscamutils#7]
`Error in if (is.na(mpd)) ...:`
`! the condition has length > 1`

This does not occur with my previous R version R-4.1.3 (that is, it runs without errors). I do get this error in 4.3.1 too; not sure about other versions. I looked a bit in the NEWS for R releases and did not see anything.

https://github.com/pbs-assess/gfiscamutils/blob/a18d00b56e9bb6720a64a260dd6327516df38d92/R/load-models.R#L1605

Occurs when compiling the [herringsr](https://github.com/pbs-assess/herringsr) PDF in the part where we build the R data model files. Full error message:

`processing file: HerringSR.Rmd`
                                                                                                                            
`Error in if (is.na(mpd)) ...:`
`! the condition has length > 1`
`Backtrace:`
` 1. gfiscamutils::build_herring_rdata_files(...)`
` 2. base::lapply(...)`
`      at gfiscamutils/R/load-models.R:8:3`
` 3. gfiscamutils (local) FUN(X[[i]], ...)`
` 4. gfiscamutils::create.rdata.file(...)`
`      at gfiscamutils/R/load-models.R:24:22`
` 5. gfiscamutils::load.iscam.files(model.dir, ...)`
`      at gfiscamutils/R/load-models.R:73:3`
` 6. gfiscamutils::calc.ahat(model)`
`      at gfiscamutils/R/load-models.R:111:3`

`Quitting from lines 174-194 [models] (HerringSR.Rmd)`
`Execution halted`

It would take some time to make a reproducible example but I can do that if required.

**Comment by cgrandin** [comment]
I don't think there's been any changes to `is.na()`, it's probably a change in the length of mpd list from 1 to something greater than 1. But `is.na()` is vectorized, so if it is passed a list or vector then it returns a logical vector and the `if()` statement will fail.

I always at least do this for every if statement - which works for a list as well as a single value:
```
if (is.na(mpd[1])){
}
```
or this if I want to check to see if any oif the list elements are `NA`
```
if (any(is.na(mpd))){
}
```

There's probably a better way I don't know about.

The changelog for R is here in case you ever need to check it (I don't see anything for this):
https://cran.r-project.org/doc/manuals/r-release/NEWS.html
